#!/bin/bash

function usage(){
	printf "使用方法：\n"
	printf "        `basename $0` [-o output] [-s size] [-l logopath] content\n"
	printf "\n"
	printf "说明：\n"
	printf "         -o output    输出文件，png 格式，省略则会使用 swing 显示\n"
	printf "         -s size      图片大小，缺省为 460\n"
	printf "         -l logopath  logo 文件的地址，可以是 url\n"
	printf "         content      二维码中所要包含的内容\n"
}

while getopts :o:s:l:h opt
do
    case $opt in
        o)
			output=$OPTARG
            ;;
        s)
			size=$OPTARG
            ;;
        l)
			logopath=$OPTARG
            ;;
        h)
			usage
			exit 0
            ;;
        ?)
			usage
			exit 1
            ;;
    esac
done

shift $((OPTIND -1))

content=$1
if [ -z "$content" ]; then
	usage
	exit 1
fi

realfile=`readlink -f $0`
workdir=`dirname $realfile`

cd "$workdir"
mvn exec:java -Dexec.args="$output $size $logopath $content"
